### PR TITLE
Created intermediate enum for events

### PR DESCRIPTION
**Pull request by VictorKoenders**
- Adds an `Event` enum that also gets send to the `EventHandler`
- Adds a way to get the total elapsed time since the game started; `app.timer.total_time()`
- Adds a way to get a reference to the underlying `glow` handle
  - I needed to make this an `Arc<>` for https://docs.rs/egui_glow/latest/egui_glow/painter/struct.Painter.html#method.new
- Added a new event `WindowResized` that gets triggered when a window gets resized
- Made `Gamepad` a wrapper around `Rc<GamepadInner>` so this could be cloneable (since it's used in `Event`)
- Added Keys `RightShift`, `RightCtrl`, `RightAlt`, `LeftCommand`, and `RightCommand`

### CODE REVIEW

**Comment by 17cupsofcoffee** [comment]
Sorry for delay on reviewing this, dayjob has been a bit crazy recently! I will try to get to it soon :)

**Comment by VictorKoenders** [comment]
No worries, take your time!

**Review by 17cupsofcoffee — COMMENTED** [review]
This all looks like reasonable changes to me - the only bit I'm mulling over slightly is the controller events returning joystick IDs (as there's nowhere else in the API you can actually use those - all the `Input` methods take a zero-indexed gamepad ID, so that you can just say 'gamepad 0' to get the first one that was plugged in).

It's a bit of a chicken and egg problem though, as at the point we convert from SDL event to our `Event`, we haven't assigned those gamepad IDs yet! So maybe it does make sense this way...

I'll give it some thought, and if I don't have any better ideas I'll merge as is 🙂

**Review by 17cupsofcoffee — APPROVED** [review]
I'm going to go with this as-is for now - can always tweak it later if I figure out a different approach to the gamepad stuff.

Thanks for the PR (and the patience waiting weeks for me to review it 😅)

**Comment by VictorKoenders** [comment]
Don't worry about it, thank you for making nova! 🙂

**Pull request merged**
